# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

CLIENT_ID: '57d3d911ff97b866533eaec8dd6168a9d99b6b75b095dc817a0b0192d1906ad1'
CLIENT_SECRET: 'aaa2a3c912a5da9774b23228a2e3a93076427084f40ab2cde488165378c45b9e'
REDIRECT_URL: 'http://localhost:3000/welcome/callback'
