# Add configuration values here, as shown below.
#
# CLIENT_ID: '7381a978f7dd7f9a1117'
#
# CLIENT SECRET: abdc3b896a0ffb85d373
CLIENT_ID: ''
CLIENT_SECRET: ''
REDIRECT_URL: 'http://localhost:3000/welcome/callback'
